### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ivome** [MoritzStefaner/ach-ingen-zell#13]
This is a really great project! @MoritzStefaner Could you add a license to the repository? 
I saw that @chroth7 has used parts of the code in his project https://github.com/bgrsquared/places which is under MIT license. I just wanted to make sure how this codebase can be used.

**Comment by MoritzStefaner** [comment]
Added Apache license now. Thanks!

**Comment by ivome** [comment]
Wow, that was quick, thanks!
