### ISSUE TITLE
Invoking webpack-dev-server

### ISSUE THREAD

**Issue by chroth7** [MoritzStefaner/ach-ingen-zell#4]
In the README, you instruct users to run
`webpack-dev-server` (for dev)
resp.
`webpack -p`

This requires the users to have these tools available globally (or have `node_modules/.bin/`) in the PATH.

Two possible solutions I see are 
1. invoke `./node_modules/.bin/webpack-dev-server`(ugly...)
2. Use `npm run`/ scripts, which adds the `.bin` to the path automatically, see here: https://docs.npmjs.com/cli/run-script

I'd suggest the second one, let me know if you want me to file a PR!

**Comment by chroth7** [comment]
oh, I forgot to mention, and with 2., you can easily pass along the `NODE_ENV=production` variable, as per https://facebook.github.io/react/downloads.html#npm

**Comment by MoritzStefaner** [comment]
Yes, sounds good! Do you know how to set this up?

**Comment by chroth7** [comment]
Cool, will send a PR with a bit of explanation later! (currently just looking into the performance a bit :) )

**Comment by chroth7** [comment]
PR sent here: https://github.com/MoritzStefaner/ach-ingen-zell/pull/5
Let me know if you have any questions!
